name: Deploy index.html

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copiar apenas index.html
        run: |
          mkdir site
          cp public/index.html site/index.html
          cp -r public/assets site/assets  # (se tiver imagens)

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
