name: Deploy index.html with Supabase key injection

on:
  push:
    branches: [main]  # ou outro branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar pasta de deploy com index.html
        run: |
          mkdir deploy
          cp public/index.html deploy/index.html

      - name: Injetar Supabase Key no index.html
        run: |
          sed -i "s/SUPABASE_KEY_PLACEHOLDER/${{ secrets.SUPABASE_KEY }}/g" deploy/index.html

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
