name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou master, se for o seu caso

permissions:
  contents: write  # necessário para permitir push via GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build (caso necessário)
        run: echo "Nenhuma build necessária para HTML estático"

      - name: Deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
